services:
  quizlab:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    env_file:
      - .env
    volumes:
      - ./data:/home/uv-app-user/app/data
    networks:
      - project_network

  quizlab-frontend:
    container_name: quizlab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9081:9081
    env_file:
      - .env
    networks:
      - project_network

networks:
  project_network:
    external: true